service: nextjs-testing

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 128
  stage: prod
  region: eu-central-1
  timeout: 15
  environment:
    NODE_ENV: production

functions:
  next:
    handler: index.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{any+}
          method: ANY

package:
  include:
    - .next/**

plugins:
  - serverless-offline
